//! Numeric regressions and independent, airless references. Legacy C/Stellarium tests remain untouched.
//! The phase-0 envelopes below describe the current approximation, not phase-6 accuracy certification.

#[path = "fixtures/current_positions.rs"]
mod baseline;

use astroterm::astro::{Horizontal, ObjectClass, Observer, accuracy_target_arcseconds};
use astroterm::catalog::load_embedded_catalog;
use astroterm::sky::{Sky, update_sky_positions};
use astroterm::timing::StepTimes;

fn boston_sky(julian_date_ut1: f64) -> Sky {
    let mut sky = Sky::from_catalog(&load_embedded_catalog().unwrap());
    let observer = Observer {
        latitude: 42.3601_f64.to_radians(),
        longitude: -71.0589_f64.to_radians(),
    };
    update_sky_positions(
        &mut sky,
        julian_date_ut1,
        &observer,
        f64::INFINITY,
        &mut StepTimes::default(),
    );
    sky
}

fn find_position(sky: &Sky, name: &str) -> Horizontal {
    if name == "Moon" {
        return sky.moon.horizontal_position();
    }
    if let Some(planet) = sky.planets.iter().find(|planet| planet.kind.name() == name) {
        return planet.horizontal_position();
    }
    sky.stars
        .iter()
        .find(|star| sky.star_name(star) == Some(name))
        .unwrap()
        .horizontal_position()
}

/// atan2 of cross-product length and dot product remains stable near zero and across azimuth wrap.
fn separation_arcseconds(a: Horizontal, b: Horizontal) -> f64 {
    let (a, b) = (a.to_unit_vector(), b.to_unit_vector());
    let cross_length =
        ((a.y * b.z - a.z * b.y).powi(2) + (a.z * b.x - a.x * b.z).powi(2) + (a.x * b.y - a.y * b.x).powi(2)).sqrt();
    cross_length.atan2(a.dot(b)).to_degrees() * 3600.0
}

#[test]
fn selected_positions_preserve_the_current_model_at_three_epochs() {
    for &(date, name, azimuth, altitude) in baseline::POSITIONS {
        let actual = find_position(&boston_sky(date), name);
        let error = separation_arcseconds(actual, Horizontal { azimuth, altitude });
        assert!(error <= 0.01, "{date} {name}: {error} arcsec");
    }
}

#[test]
fn boston_positions_match_independent_references_with_documented_current_errors() {
    // Source/parameters/versions and raw responses: tests/fixtures/reference, generated by scripts/reference.
    // Horizons uses TT 2459146.000800741 for UTC 2459146.0; our legacy pipeline currently sets TT=UT1.
    let references: serde_json::Value =
        serde_json::from_str(include_str!("fixtures/reference/references.json")).unwrap();
    let sky = boston_sky(2459146.0);
    for body in references["horizons_boston"].as_array().unwrap() {
        let name = body["name"].as_str().unwrap();
        let row = &body["rows"][0];
        let angle = |field: &str| row[field].as_str().unwrap().parse::<f64>().unwrap().to_radians();
        let reference = Horizontal {
            azimuth: angle("Azimuth_(a-app)"),
            altitude: angle("Elevation_(a-app)"),
        };
        let error = separation_arcseconds(find_position(&sky, name), reference);
        let (class, current_limit) = match name {
            "Sun" => (ObjectClass::SunAndPlanets, 15.0),
            "Mars" => (ObjectClass::SunAndPlanets, 250.0),
            "Neptune" => (ObjectClass::SunAndPlanets, 80.0),
            "Moon" => (ObjectClass::Moon, 150.0),
            _ => unreachable!(),
        };
        let future_target = accuracy_target_arcseconds(class, 2459146.000800741).unwrap();
        eprintln!("{name}: {error:.3} arcsec; current envelope {current_limit}, future target {future_target}");
        assert!(error < current_limit, "{name}: {error} arcsec");
    }
    for star in references["boston_stars"].as_array().unwrap() {
        let actual = find_position(&sky, star["name"].as_str().unwrap());
        for (field, limit) in [("apparent_az_alt_rad", 30.0), ("matched_legacy_mean_az_alt_rad", 0.1)] {
            let coordinates = &star[field];
            let reference = Horizontal {
                azimuth: coordinates[0].as_f64().unwrap(),
                altitude: coordinates[1].as_f64().unwrap(),
            };
            let error = separation_arcseconds(actual, reference);
            assert!(error < limit, "{} {field}: {error} arcsec", star["name"]);
        }
    }
}
